name = "Minecraft"
display_name = "Minecraft"
default_url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/{{version}}/minecraft.apworld"

[versions]
"0.1.3+hotfix" = { local = "../apworlds/minecraft.apworld" }
"0.1.5+hotfix" = { url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/0.1.5_hotfix/minecraft.apworld" }
"0.1.6+hotfix" = { url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/0.1.6_hotfix/minecraft.apworld" }
"0.1.7+hotfix" = { url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/0.1.7_hotfix/minecraft.apworld" }
