name = "Minecraft Dig"
home = "https://discord.com/channels/731205301247803413/837136185662111746"
default_url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/{{version}}_dig/minecraft_dig.apworld"

[versions]
"0.0.1+0.1.6.hotfix" = { url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/0.1.6_hotfix/minecraft_dig.apworld" }
"0.0.1+0.1.7.hotfix" = { url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/0.1.7_hotfix/minecraft_dig.apworld" }
"0.0.5+dig" = { url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/0.0.5_dig/minecraft_dig.apworld" }
"0.0.6+dig" = { url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/APWorld_Dig_v0.0.6/minecraft_dig.apworld" }
"0.0.7+dig" = { url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/0.0.7_dig/minecraft_dig.apworld" }
"0.0.10" = {}
"0.0.11" = {}
